import type { Course } from "../types/course";

export const COURSES_DATA: Record<string, Course> = {
  "v-act": {
    id: "v-act",
    title: "V-ACT",
    tag: "ĐGNL TP.HCM",
    subtitle: "Đánh giá Năng lực — ĐHQG TP.HCM",
    desc: "Kỳ thi đánh giá toàn diện các năng lực: ngôn ngữ, tư duy logic, giải quyết vấn đề trên giấy, do Đại học Quốc gia TP.HCM tổ chức để xét tuyển đại học.",
    img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=60&auto=format&fit=crop",
    headerBg: "bg-[#18321b]",
    cardHeaderBg: "bg-[#dce9de]",
    cardBtnColor: "bg-[#28522d] hover:bg-[#1e4022]",
    subjects: [
      { id: "tieng-viet", title: "Tiếng Việt", duration: "30 giờ", lessons: 40 },
      { id: "tieng-anh", title: "Tiếng Anh", duration: "42 giờ", lessons: 56 },
      { id: "toan-hoc", title: "Toán học", duration: "42 giờ", lessons: 56 },
      { id: "vat-ly", title: "Vật lý", duration: "28 giờ", lessons: 36 },
      { id: "hoa-hoc", title: "Hóa học", duration: "28 giờ", lessons: 36 },
      { id: "sinh-hoc", title: "Sinh học", duration: "22 giờ", lessons: 28 },
      { id: "lich-su", title: "Lịch sử", duration: "20 giờ", lessons: 24 },
      { id: "dia-ly", title: "Địa lý", duration: "20 giờ", lessons: 24 },
    ],
  },
  "v-sat": {
    id: "v-sat",
    title: "V-SAT",
    tag: "Khảo thí quốc gia",
    subtitle: "Kỳ thi đánh giá năng lực theo môn học",
    desc: "Kỳ thi đánh giá năng lực theo từng môn học độc lập: Toán, Văn, Anh, Lý, Hóa, Sinh, Sử, Địa hoàn toàn trên máy tính, do các trường đại học phối hợp tổ chức.",
    img: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=60&auto=format&fit=crop",
    headerBg: "bg-[#132c37]",
    cardHeaderBg: "bg-[#e3edf7]",
    cardBtnColor: "bg-[#1d3d54] hover:bg-[#152e3f]",
    subjects: [
      { id: "toan", title: "Toán", duration: "48 giờ", lessons: 64 },
      { id: "vat-ly", title: "Vật lý", duration: "36 giờ", lessons: 48 },
      { id: "hoa-hoc", title: "Hóa học", duration: "36 giờ", lessons: 48 },
      { id: "sinh-hoc", title: "Sinh học", duration: "30 giờ", lessons: 40 },
      { id: "lich-su", title: "Lịch sử", duration: "24 giờ", lessons: 32 },
      { id: "dia-ly", title: "Địa lý", duration: "24 giờ", lessons: 32 },
      { id: "tieng-anh", title: "Tiếng Anh", duration: "48 giờ", lessons: 64 },
      { id: "ngu-van", title: "Ngữ văn", duration: "36 giờ", lessons: 48 },
    ],
  },
  "hsa": {
    id: "hsa",
    title: "HSA",
    tag: "ĐGNL ĐHQG Hà Nội",
    subtitle: "Đánh giá Năng lực — ĐHQG Hà Nội",
    desc: "Kỳ thi đánh giá toàn diện năng lực: tư duy định lượng, định tính và khoa học; trên máy tính, do Đại học Quốc gia Hà Nội tổ chức.",
    img: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=60&auto=format&fit=crop",
    headerBg: "bg-[#2e2a0b]",
    cardHeaderBg: "bg-[#fdf4e3]",
    cardBtnColor: "bg-[#6e5005] hover:bg-[#523c04]",
    subjects: [
      { id: "toan-hoc", title: "Toán học", duration: "48 giờ", lessons: 64 },
      { id: "van-hoc", title: "Văn học", duration: "36 giờ", lessons: 48 },
      { id: "vat-ly", title: "Vật lý", duration: "30 giờ", lessons: 40 },
      { id: "hoa-hoc", title: "Hóa học", duration: "30 giờ", lessons: 40 },
      { id: "sinh-hoc", title: "Sinh học", duration: "24 giờ", lessons: 32 },
      { id: "lich-su", title: "Lịch sử", duration: "22 giờ", lessons: 28 },
      { id: "dia-ly", title: "Địa lý", duration: "22 giờ", lessons: 28 },
      { id: "ngoai-ngu", title: "Ngoại ngữ", duration: "36 giờ", lessons: 48 },
    ],
  },
  "hsca": {
    id: "hsca",
    title: "HSCA",
    tag: "ĐH Sư phạm TP.HCM",
    subtitle: "Đánh giá Năng lực chuyên biệt — ĐHSP TP.HCM",
    desc: "Đánh giá năng lực chuyên biệt do Trường Đại học Sư phạm TP.HCM tổ chức, chủ yếu dùng để xét tuyển khối ngành Sư phạm và Giáo dục.",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=60&auto=format&fit=crop",
    headerBg: "bg-[#2d152c]",
    cardHeaderBg: "bg-[#f5e8f5]",
    cardBtnColor: "bg-[#7e3b7b] hover:bg-[#612c5f]",
    subjects: [
      { id: "toan", title: "Toán", duration: "40 giờ", lessons: 54 },
      { id: "vat-ly", title: "Vật lý", duration: "32 giờ", lessons: 42 },
      { id: "hoa-hoc", title: "Hóa học", duration: "32 giờ", lessons: 42 },
      { id: "sinh-hoc", title: "Sinh học", duration: "26 giờ", lessons: 34 },
      { id: "ngu-van", title: "Ngữ văn", duration: "30 giờ", lessons: 40 },
      { id: "tieng-anh", title: "Tiếng Anh", duration: "36 giờ", lessons: 48 },
    ],
  },
  "thpt-qg": {
    id: "thpt-qg",
    title: "THPT QG",
    tag: "Bộ GD&ĐT",
    subtitle: "Kỳ thi Tốt nghiệp THPT Quốc Gia",
    desc: "Kỳ thi Tốt nghiệp THPT Quốc Gia do Bộ Giáo dục và Đào tạo tổ chức hàng năm, vừa xét tốt nghiệp THPT vừa là cơ sở xét tuyển đại học.",
    img: "https://images.unsplash.com/photo-1557800636-894a64c1696f?w=800&q=60&auto=format&fit=crop",
    headerBg: "bg-[#163645]",
    cardHeaderBg: "bg-[#e2eef7]",
    cardBtnColor: "bg-[#1b4357] hover:bg-[#133242]",
    subjects: [
      { id: "toan", title: "Toán", duration: "48 giờ", lessons: 64 },
      { id: "van", title: "Văn", duration: "36 giờ", lessons: 48 },
      { id: "anh", title: "Anh", duration: "36 giờ", lessons: 48 },
      { id: "sinh", title: "Sinh", duration: "24 giờ", lessons: 32 },
      { id: "su", title: "Sử", duration: "20 giờ", lessons: 28 },
      { id: "dia", title: "Địa", duration: "20 giờ", lessons: 28 },
    ],
  },
};
