export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (courseId: string | number = ':courseId') => `/courses/${courseId}`,
  TRIAL: '/trial',
  DOCUMENTS: '/documents',
  ABOUT: '/about',
  VIP: '/vip',
  NOT_FOUND: '/404',
  UNDER_DEVELOPMENT: '/under-development',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
  },
  LEARNER: {
    ROOT: '/learner',
    DASHBOARD: '/learner/dashboard',
  },
  ASSISTANT: {
    ROOT: '/assistant',
    DASHBOARD: '/assistant/dashboard',
    COURSES: '/assistant/courses',
    COURSE_DETAIL: (courseKey: string = ':courseKey') => `/assistant/courses/${courseKey}`,
    COURSE_UPLOAD_EXAM: (courseKey: string = ':courseKey') => `/assistant/courses/${courseKey}/upload-exam`,
    COURSE_EDIT_EXAM: (courseKey: string = ':courseKey', examId: string | number = ':examId') => `/assistant/courses/${courseKey}/edit-exam/${examId}`,
    COURSE_SUBJECT_DETAIL: (courseKey: string = ':courseKey', subjectName: string = ':subjectName') => `/assistant/courses/${courseKey}/${subjectName}`,
    MATERIALS: '/assistant/materials',
    STUDENTS: '/assistant/students',
    FLASHCARDS: '/assistant/flashcards',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    SYSTEM: '/admin/system',
    WEBSITE: '/admin/website',
  },
} as const;
