export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (courseId: string | number = ':courseId') => `/courses/${courseId}`,
  TRIAL: '/trial',
  DOCUMENTS: '/documents',
  ABOUT: '/about',
  VIP: '/vip',
  NOT_FOUND: '/404',
  UNDER_DEVELOPMENT: '/under-development',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
  },
  LEARNER: {
    ROOT: '/learner',
    DASHBOARD: '/learner/dashboard',
    PROFILE: '/learner/profile',
    MY_COURSES: '/learner/my-courses',
    SUBJECT_DETAIL: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId') => `/learner/courses/${courseId}/subjects/${subjectId}`,
    EXAM_START: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', examId: string | number = ':examId') => `/learner/courses/${courseId}/subjects/${subjectId}/exams/${examId}/start`,
    TAKE_EXAM: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', examId: string | number = ':examId') => `/learner/courses/${courseId}/subjects/${subjectId}/exams/${examId}/take`,
    EXERCISE_START: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', exerciseId: string | number = ':exerciseId') => `/learner/courses/${courseId}/subjects/${subjectId}/exercises/${exerciseId}/start`,
    TAKE_EXERCISE: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', exerciseId: string | number = ':exerciseId') => `/learner/courses/${courseId}/subjects/${subjectId}/exercises/${exerciseId}/take`,
    FLASHCARD_TOPICS: '/learner/flashcards',
    FLASHCARD_STUDY: (topicId: string | number = ':topicId') => `/learner/flashcards/${topicId}/study`,
  },
  ASSISTANT: {
    ROOT: '/assistant',
    DASHBOARD: '/assistant/dashboard',
    COURSES: '/assistant/courses',
    COURSE_DETAIL: (courseKey: string = ':courseKey') => `/assistant/courses/${courseKey}`,
    COURSE_UPLOAD_EXAM: (courseKey: string = ':courseKey') => `/assistant/courses/${courseKey}/upload-exam`,
    COURSE_EDIT_EXAM: (courseKey: string = ':courseKey', examId: string | number = ':examId') => `/assistant/courses/${courseKey}/edit-exam/${examId}`,
    COURSE_SUBJECT_DETAIL: (courseKey: string = ':courseKey', subjectName: string = ':subjectName') => `/assistant/courses/${courseKey}/${subjectName}`,
    MATERIALS: '/assistant/materials',
    STUDENTS: '/assistant/students',
    FLASHCARDS: '/assistant/flashcards',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    SYSTEM: '/admin/system',
    WEBSITE: '/admin/website',
    ACTIVITIES: '/admin/system/activities',
  },
} as const;
