export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (courseId: string | number = ':courseId') => `/courses/${courseId}`,
  TRIAL: '/trial',
  DOCUMENTS: '/documents',
  ABOUT: '/about',
  VIP: '/vip',
  NOT_FOUND: '/404',
  UNDER_DEVELOPMENT: '/under-development',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
  },
  LEARNER: {
    ROOT: '/learner',
    DASHBOARD: '/learner/dashboard',
    PROFILE: '/learner/profile',
    MY_COURSES: '/learner/my-courses',
    SUBJECT_DETAIL: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId') => `/learner/courses/${courseId}/subjects/${subjectId}`,
    EXAM_START: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', examId: string | number = ':examId') => `/learner/courses/${courseId}/subjects/${subjectId}/exams/${examId}`,
    TAKE_EXAM: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', examId: string | number = ':examId') => `/learner/courses/${courseId}/subjects/${subjectId}/exams/${examId}/take`,
    EXERCISE_START: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', exerciseId: string | number = ':exerciseId') => `/learner/courses/${courseId}/subjects/${subjectId}/exercises/${exerciseId}`,
    TAKE_EXERCISE: (courseId: string | number = ':courseId', subjectId: string | number = ':subjectId', exerciseId: string | number = ':exerciseId') => `/learner/courses/${courseId}/subjects/${subjectId}/exercises/${exerciseId}/take`,
  },
  ASSISTANT: {
    ROOT: '/assistant',
    DASHBOARD: '/assistant/dashboard',
    COURSES: '/assistant/courses',
    MATERIALS: '/assistant/materials',
    STUDENTS: '/assistant/students',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    SYSTEM: '/admin/system',
    WEBSITE: '/admin/website',
  },
} as const;
