name: Study Web FE CD

on:
   workflow_run:
    workflows: ["ReactJS CI Pipeline"]
    types:
      - completed
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/frontend
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  GITOPS_REPO: CUS-Study-Web/study-web-gitops

concurrency:
  group: fe-deploy
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format image name to lowercase
        run: echo "IMAGE_NAME_LOWER=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout GitOps Manifests
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: gitops-manifests
          ref: main
      - name: Deploy Locally on Self-Hosted
        env:
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          cd gitops-manifests
          IMAGE_TAG=$IMAGE_TAG make fe
